<?php

namespace App\Tasks\Swoole;

use App\Core\Cli\Task\Socket;
use swoole_server;
use swoole_process;

class SocketTask extends Socket
{
    protected function events()
    {
        return [
            'connect' => [$this, 'connect'],
            'receive' => [$this, 'receive'],
            'close' => [$this, 'close'],
        ];
    }

    protected function beforeServerStart(swoole_server $server)
    {
        parent::beforeServerStart($server); // TODO: Change the autogenerated stub
        $process = new swoole_process(function ($process) use ($server) {
            // while (true) {
            // echo 'tick:' . time() . PHP_EOL;
            //     sleep(1);
            // }
            $server->tick(1000, function () {
                echo 'tick:' . time() . PHP_EOL;
            });
        });

        $server->addProcess($process);

    }


    public function connect(swoole_server $server, $fd, $from_id)
    {
        echo 'connect' . PHP_EOL;
    }

    public function receive(swoole_server $server, $fd, $reactor_id, $data)
    {
        $data = 'receive:' . $data;
        echo $data;
        $server->send($fd, $data);
    }

    public function close(swoole_server $server, $fd, $reactorId)
    {
        echo 'close' . PHP_EOL;
    }

}

